<?php

namespace Onlinestore\BooksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooksRepository extends EntityRepository
{
}
