<?php

namespace Onlinestore\BooksBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ordersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ordersRepository extends EntityRepository
{
}
